### ISSUE TITLE
SMB Utility on Android (.APK) build for Phones, Tablets?

### ISSUE THREAD

**Issue by ghost** [bonimy/SMB-Utility#12]
Is it possible to **PORT** SMB Utility for **Google Android / Google Chrome OS (.APK)** platform (Phones, Tablets, Laptops)

The **minimum API** will be: **API 21 (Android 5.0)**
The **target API** will be: **API 28 (Android 9.0)**

File: SMB_Utility.apk

Android Phones, Tablets are multi-touch screen
Chrome OS is a Laptop

**Comment by bonimy** [comment]
Hi @Squidward22. So far, I'm the only programmer working on SMB Utility anymore, and I do not have a Java background (which the Android API requires). If time were an infinite resource, I would love to port this to Android. However, SMB Utility is a low priority project for me these days, and -when I do work on it- there are much higher priority tasks I am trying to do with it than port it to Android.

So, to answer your question: is it possible? Absolutely it is and I'd love to see it. But, will I be doing it? Afraid not. And I honestly don't want to make plans to. However, if you would like to see this ported to Android, and you (or someone you know) has experience doing that and would want to, I'd be happy to encourage you (or them) and share what knowledge I have with SMB Utility to help make that happen.

If you'd like to be an Android porter, let me know and I'll keep this issue open, otherwise, I'll be closing it as "out of scope" within a few days to a week.
